using eMekteb.Services.Database;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace eMekteb.Services.Seed
{
    public static class KorisnikData
    {
        public static void SeedData(this EntityTypeBuilder<Korisnik> entity)
        {
            entity.HasData(
                new Korisnik
                {
                    Id = 1,
                    Ime = "Dino",
                    Prezime = "Maksumic",
                    Username = "admin",
                    Telefon = "063355441",
                    Mail = "dino@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1985, 09, 12),
                    ImeRoditelja = "Mehmed",
                    MektebId = 1,
                    LozinkaHash = "dP9XoZcTTTU8f4ddDbNLJalRQqQ=",
                    LozinkaSalt = "jmK1d1xnmg2DC0svh3UvRw=="
                },
                new Korisnik
                {
                    Id = 2,
                    Ime = "Zijad",
                    Prezime = "Maric",
                    Username = "roditelj",
                    Telefon = "062627878",
                    Mail = "zijad@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1971, 09, 12),
                    ImeRoditelja = "Bajro",
                    MektebId = 1,
                    LozinkaHash = "z/sT0B+tdXeEL9SHGZRnuwLTq24=",
                    LozinkaSalt = "TojKLl0mMwNiLEbjjO9oZg==",
                
                },
                new Korisnik
                {
                    Id = 3,
                    Ime = "Lejla",
                    Prezime = "Maric",
                    Username = "ucenik",
                    Telefon = "062627878",
                    Mail = "lejla@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2001, 09, 12),
                    ImeRoditelja = "Zijad",
                    MektebId = 1,
                    LozinkaHash = "YumKKJBN/A/I4N5FUZAQiS+GsKU=",
                    LozinkaSalt = "sDj4ejrFF0VUWuf3Z86EAg==",
                    RoditeljId = 2
                },
                new Korisnik
                {
                    Id = 4,
                    Ime = "Armin",
                    Prezime = "Abaza",
                    Username = "komisija",
                    Telefon = "062545121",
                    Mail = "armin@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1981, 09, 12),
                    ImeRoditelja = "Aner",
                    MektebId = 1,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA=="
                },
                new Korisnik
                {
                    Id = 5,
                    Ime = "Atif",
                    Prezime = "Mujkic",
                    Username = "imam",
                    Telefon = "062589989",
                    Mail = "atif@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1989, 09, 12),
                    ImeRoditelja = "Suad",
                    MektebId = 1,
                    LozinkaHash = "cKnCCVJWJjRXqM7XevrbN6B3RbM=",
                    LozinkaSalt = "cLnMQzMpSBWfc9nVetCRnw=="
                },
                new Korisnik
                {
                    Id = 6,
                    Ime = "Sadzid",
                    Prezime = "Maric",
                    Username = "sadzid",
                    Telefon = "062627878",
                    Mail = "sadzid@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2003, 09, 12),
                    ImeRoditelja = "Zijad",
                    MektebId = 1,
                    LozinkaHash = "ScUPKxksw9aYsTBy3ONHNtiP/pQ=",
                    LozinkaSalt = "iHcegpYjjbOop1BEsE3Rtg==",
                    RoditeljId = 2
                },
                new Korisnik
                {
                    Id = 8,
                    Ime = "Omer",
                    Prezime = "Gosto",
                    Username = "omer",
                    Telefon = "062062062",
                    Mail = "omer@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2001, 09, 12),
                    ImeRoditelja = "Almir",
                    MektebId = 2,
                    LozinkaHash = "LCG4lHMiiZiASdZwtCYMsGxbIoc=",
                    LozinkaSalt = "lTkuZDGh2IQr66IeRWnkIA==",
                    RoditeljId = 7
                },
                new Korisnik
                {
                    Id = 9,
                    Ime = "Nejra",
                    Prezime = "Gosto",
                    Username = "nejra",
                    Telefon = "062062062",
                    Mail = "nejra@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2003, 09, 12),
                    ImeRoditelja = "Almir",
                    MektebId = 2,
                    LozinkaHash = "YumKKJBN/A/I4N5FUZAQiS+GsKU=",
                    LozinkaSalt = "sDj4ejrFF0VUWuf3Z86EAg==",
                    RoditeljId = 7
                },
                new Korisnik
                {
                    Id = 10,
                    Ime = "Amer",
                    Prezime = "Gosto",
                    Username = "amer",
                    Telefon = "062062062",
                    Mail = "amer@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2005, 09, 12),
                    ImeRoditelja = "Almir",
                    MektebId = 2,
                    LozinkaHash = "YumKKJBN/A/I4N5FUZAQiS+GsKU=",
                    LozinkaSalt = "sDj4ejrFF0VUWuf3Z86EAg==",
                    RoditeljId = 7
                },
                new Korisnik
                {
                    Id = 12,
                    Ime = "Madzid",
                    Prezime = "Lizde",
                    Username = "madzid",
                    Telefon = "063063063",
                    Mail = "madzid@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2009, 09, 12),
                    ImeRoditelja = "Almir",
                    MektebId = 3,
                    LozinkaHash = "/VHd1Q8gLYi2VggsmwT3ruCAqJk=",
                    LozinkaSalt = "HzWzHz3sQE9LK4+jteknTA==",
                    RoditeljId = 11
                },
                new Korisnik
                {
                    Id = 13,
                    Ime = "Hazim",
                    Prezime = "Lizde",
                    Username = "hazim",
                    Telefon = "063063063",
                    Mail = "hazim@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2008, 09, 12),
                    ImeRoditelja = "Almir",
                    MektebId = 3,
                    LozinkaHash = "YumKKJBN/A/I4N5FUZAQiS+GsKU=",
                    LozinkaSalt = "sDj4ejrFF0VUWuf3Z86EAg==",
                    RoditeljId = 11
                },
                new Korisnik
                {
                    Id = 14,
                    Ime = "Alma",
                    Prezime = "Lizde",
                    Username = "alma.lizde",
                    Telefon = "063063063",
                    Mail = "almal@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2000, 09, 12),
                    ImeRoditelja = "Almir",
                    MektebId = 3,
                    LozinkaHash = "YumKKJBN/A/I4N5FUZAQiS+GsKU=",
                    LozinkaSalt = "sDj4ejrFF0VUWuf3Z86EAg==",
                    RoditeljId = 11
                },
                new Korisnik
                {
                    Id = 16,
                    Ime = "Iman",
                    Prezime = "Terko",
                    Username = "iman.terko",
                    Telefon = "061061061",
                    Mail = "imant@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2007, 09, 12),
                    ImeRoditelja = "Muamer",
                    MektebId = 2,
                    LozinkaHash = "5SBNe56lKlnvUcxOHVIpujXsv5g=",
                    LozinkaSalt = "+HLQg+K0DVk1praxlrTU3g==",
                    RoditeljId = 15
                },
                new Korisnik
                {
                    Id = 17,
                    Ime = "Emina",
                    Prezime = "Terko",
                    Username = "emina.terko",
                    Telefon = "061061061",
                    Mail = "emina@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2002, 09, 12),
                    ImeRoditelja = "Muamer",
                    MektebId = 2,
                    LozinkaHash = "YumKKJBN/A/I4N5FUZAQiS+GsKU=",
                    LozinkaSalt = "sDj4ejrFF0VUWuf3Z86EAg==",
                    RoditeljId = 15
                },
                new Korisnik
                {
                    Id = 7,
                    Ime = "Almir",
                    Prezime = "Gosto",
                    Username = "almir.gosto",
                    Telefon = "062062062",
                    Mail = "almir@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1971, 09, 12),
                    ImeRoditelja = "Salko",
                    MektebId = 2,
                    LozinkaHash = "bkLKbSxLPSFFmeMtQgdPC1AAnDQ=",
                    LozinkaSalt = "Gx+JkCnY/r169UVKD+dWYg==",

                },
                new Korisnik
                {
                    Id = 11,
                    Ime = "Almir",
                    Prezime = "Lizde",
                    Username = "almir.lizde",
                    Telefon = "063063063",
                    Mail = "almirL@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1974, 09, 12),
                    ImeRoditelja = "Halil",
                    MektebId = 3,
                    LozinkaHash = "QASszTjeeigPIi3z2Pco4Xz6z2A=",
                    LozinkaSalt = "SGEPRubCkiUhpIkgN1ICLA==",

                },
                new Korisnik
                {
                    Id = 15,
                    Ime = "Muamer",
                    Prezime = "Terko",
                    Username = "muamer.terko",
                    Telefon = "061061061",
                    Mail = "muamer@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1979, 09, 12),
                    ImeRoditelja = "Husein",
                    MektebId = 2,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",

                },
                new Korisnik
                {
                    Id = 18,
                    Ime = "Omer",
                    Prezime = "Brkan",
                    Username = "omer.brkan",
                    Telefon = "061222222",
                    Mail = "omer@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1979, 09, 12),
                    ImeRoditelja = "Husein",
                    MektebId = 1,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                },
                new Korisnik
                {
                    Id = 36,
                    Ime = "Anadin",
                    Prezime = "Brkan",
                    Username = "anadin.brkan",
                    Telefon = "061222222",
                    Mail = "anadin@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2000, 09, 12),
                    ImeRoditelja = "Omer",
                    MektebId = 1,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                    RoditeljId = 18
                },
                new Korisnik
                {
                    Id = 37,
                    Ime = "Zaim",
                    Prezime = "Brkan",
                    Username = "zaim.brkan",
                    Telefon = "061222222",
                    Mail = "zaim@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2008, 09, 12),
                    ImeRoditelja = "Omer",
                    MektebId = 1,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                    RoditeljId = 18
                },
                new Korisnik
                {
                    Id = 19,
                    Ime = "Voljevica",
                    Prezime = "Kenan",
                    Username = "kenan.voljevica",
                    Telefon = "061222222",
                    Mail = "kenan@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2002, 06, 14),
                    ImeRoditelja = "Omer",
                    MektebId = 1,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                    RoditeljId = 18
                },
                new Korisnik
                {
                    Id = 20,
                    Ime = "Nejra",
                    Prezime = "Brkan",
                    Username = "nejra.brkan",
                    Telefon = "061222222",
                    Mail = "nejra@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2004, 03, 17),
                    ImeRoditelja = "Omer",
                    MektebId = 1,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                    RoditeljId = 18
                },
                new Korisnik
                {
                    Id = 21,
                    Ime = "Samed",
                    Prezime = "Kodrić",
                    Username = "samed.kodric",
                    Telefon = "061222333",
                    Mail = "samed@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1979, 09, 12),
                    ImeRoditelja = "Husein",
                    MektebId = 3,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                },
                new Korisnik
                {
                    Id = 22,
                    Ime = "Ahmet",
                    Prezime = "Kodrić",
                    Username = "ahmet.kodric",
                    Telefon = "061222333",
                    Mail = "ahmet@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2001, 09, 12),
                    ImeRoditelja = "Samed",
                    MektebId = 3,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                    RoditeljId = 21
                },
                new Korisnik
                {
                    Id = 23,
                    Ime = "Elma",
                    Prezime = "Kodrić",
                    Username = "elma.kodric",
                    Telefon = "061222333",
                    Mail = "elma@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2006, 09, 12),
                    ImeRoditelja = "Samed",
                    MektebId = 3,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                    RoditeljId = 21
                },
                new Korisnik
                {
                    Id = 24,
                    Ime = "Medzida",
                    Prezime = "Pehilj",
                    Username = "medzida.pehilj",
                    Telefon = "061061444",
                    Mail = "medzida@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2005, 09, 12),
                    ImeRoditelja = "Samed",
                    MektebId = 4,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                },
                new Korisnik
                {
                    Id = 25,
                    Ime = "Bakir",
                    Prezime = "Pehilj",
                    Username = "bakir.pehilj",
                    Telefon = "061061444",
                    Mail = "bakir@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2006, 09, 12),
                    ImeRoditelja = "Samed",
                    MektebId = 4,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                },
                new Korisnik
                {
                    Id = 26,
                    Ime = "Seid",
                    Prezime = "Cikotić",
                    Username = "seid.cikotic",
                    Telefon = "062062555",
                    Mail = "seid@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2007, 08, 12),
                    ImeRoditelja = "Samed",
                    MektebId = 4,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                },
                new Korisnik
                {
                    Id = 27,
                    Ime = "Sajra",
                    Prezime = "Sarancic",
                    Username = "sajra.sarancic",
                    Telefon = "063555444",
                    Mail = "sajra@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2004, 09, 12),
                    ImeRoditelja = "Samed",
                    MektebId = 4,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                },
                new Korisnik
                {
                    Id = 28,
                    Ime = "Amina",
                    Prezime = "Čomor",
                    Username = "amina.comor",
                    Telefon = "063212454",
                    Mail = "amina@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2004, 03, 17),
                    ImeRoditelja = "Samed",
                    MektebId = 5,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                },
                new Korisnik
                {
                    Id = 29,
                    Ime = "Hana",
                    Prezime = "Omerika",
                    Username = "hana.omerika",
                    Telefon = "061474851",
                    Mail = "hana@gmail.com",
                    Spol = "Ž",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2001, 01, 23),
                    ImeRoditelja = "Samed",
                    MektebId = 6,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                },
                new Korisnik
                {
                    Id = 30,
                    Ime = "Amil",
                    Prezime = "Omerović",
                    Username = "amil.omerovic",
                    Telefon = "061111444",
                    Mail = "amil@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2001, 03, 22),
                    ImeRoditelja = "Samed",
                    MektebId = 6,
                    LozinkaHash = "AtSGH/z7qvkVdWoRnHgpVjtiw+M=",
                    LozinkaSalt = "XPD7niYAxH0Rify963NJDA==",
                },
                new Korisnik
                {
                    Id = 31,
                    Ime = "Muhjudin",
                    Prezime = "Bećoja",
                    Username = "muhjudin",
                    Telefon = "062062581",
                    Mail = "muhjudin@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1989, 09, 12),
                    ImeRoditelja = "Suad",
                    MektebId = 2,
                    LozinkaHash = "cKnCCVJWJjRXqM7XevrbN6B3RbM=",
                    LozinkaSalt = "cLnMQzMpSBWfc9nVetCRnw=="
                },
                new Korisnik
                {
                    Id = 32,
                    Ime = "Sanjin",
                    Prezime = "Šahić",
                    Username = "sanjin.sahic",
                    Telefon = "063212323",
                    Mail = "sanjin@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1999, 09, 12),
                    ImeRoditelja = "Suad",
                    MektebId = 3,
                    LozinkaHash = "cKnCCVJWJjRXqM7XevrbN6B3RbM=",
                    LozinkaSalt = "cLnMQzMpSBWfc9nVetCRnw=="
                },
                new Korisnik
                {
                    Id = 33,
                    Ime = "Muhamed",
                    Prezime = "Crnomerović",
                    Username = "muhamed.crnomerovic",
                    Telefon = "062598777",
                    Mail = "muhamed@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2000, 09, 12),
                    ImeRoditelja = "Nazif",
                    MektebId = 4,
                    LozinkaHash = "cKnCCVJWJjRXqM7XevrbN6B3RbM=",
                    LozinkaSalt = "cLnMQzMpSBWfc9nVetCRnw=="
                },
                new Korisnik
                {
                    Id = 34,
                    Ime = "Šefik",
                    Prezime = "Čavčić",
                    Username = "sefik.cavcic",
                    Telefon = "062358474",
                    Mail = "sefik@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(2000, 09, 12),
                    ImeRoditelja = "Nazif",
                    MektebId = 5,
                    LozinkaHash = "cKnCCVJWJjRXqM7XevrbN6B3RbM=",
                    LozinkaSalt = "cLnMQzMpSBWfc9nVetCRnw=="
                },
                new Korisnik
                {
                    Id = 35,
                    Ime = "Suljo",
                    Prezime = "Cikotić",
                    Username = "suljo.cikotic",
                    Telefon = "061222555",
                    Mail = "suljo@gmail.com",
                    Spol = "M",
                    Status = "Aktivan",
                    DatumRodjenja = new DateTime(1984, 09, 12),
                    ImeRoditelja = "Omer",
                    MektebId = 6,
                    LozinkaHash = "cKnCCVJWJjRXqM7XevrbN6B3RbM=",
                    LozinkaSalt = "cLnMQzMpSBWfc9nVetCRnw=="
                }



            );
        }
    }
}
